language: c
compiler: gcc
dist: trusty
sudo: required
install: make clean && make
before_script:
  - git clone -b 5.0.7 --depth 1 https://github.com/antirez/redis.git
  - cd redis
  - make
  - cd ..
  - sudo pip install redis
  - ./redis/src/redis-server --loadmodule ./module.so &
script: make test
